### ISSUE TITLE
Something wrong with 0.17.0

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-management#247]
```
sbt:streamee-demo> streamee-demo[ERROR] Exception in thread "main" java.lang.IllegalArgumentException: Illegal [akka.discovery.akka-dns.class] value or incompatible class! The implementation class MUST extend akka.discovery.SimpleServiceDiscovery and take an ExtendedActorSystem as constructor argument.
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery.$anonfun$createServiceDiscovery$1(ServiceDiscovery.scala:81)
streamee-demo[ERROR] 	at scala.util.Failure.getOrElse(Try.scala:218)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery.akka$discovery$ServiceDiscovery$$createServiceDiscovery(ServiceDiscovery.scala:78)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery$$anon$1.apply(ServiceDiscovery.scala:15)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery$$anon$1.apply(ServiceDiscovery.scala:14)
streamee-demo[ERROR] 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery.loadServiceDiscovery(ServiceDiscovery.scala:46)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery._simpleImpl$lzycompute(ServiceDiscovery.scala:28)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery._simpleImpl(ServiceDiscovery.scala:28)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery.discovery(ServiceDiscovery.scala:34)
streamee-demo[ERROR] 	at akka.management.cluster.bootstrap.ClusterBootstrap.<init>(ClusterBootstrap.scala:46)
streamee-demo[ERROR] 	at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:133)
streamee-demo[ERROR] 	at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:127)
streamee-demo[ERROR] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
streamee-demo[ERROR] 	at akka.management.AkkaManagement.$anonfun$loadRouteProviders$1(AkkaManagement.scala:192)
streamee-demo[ERROR] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
streamee-demo[ERROR] 	at scala.collection.immutable.List.foreach(List.scala:389)
streamee-demo[ERROR] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
streamee-demo[ERROR] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
streamee-demo[ERROR] 	at scala.collection.immutable.List.map(List.scala:295)
streamee-demo[ERROR] 	at akka.management.AkkaManagement.loadRouteProviders(AkkaManagement.scala:178)
streamee-demo[ERROR] 	at akka.management.AkkaManagement.<init>(AkkaManagement.scala:40)
streamee-demo[ERROR] 	at akka.management.AkkaManagement$.createExtension(AkkaManagement.scala:30)
streamee-demo[ERROR] 	at akka.management.AkkaManagement$.createExtension(AkkaManagement.scala:24)
streamee-demo[ERROR] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
streamee-demo[ERROR] 	at akka.actor.ExtensionId.apply(Extension.scala:79)
streamee-demo[ERROR] 	at akka.actor.ExtensionId.apply$(Extension.scala:78)
streamee-demo[ERROR] 	at akka.management.AkkaManagement$.apply(AkkaManagement.scala:24)
streamee-demo[ERROR] 	at io.moia.streamee.demo.Main$.main(Main.scala:33)
streamee-demo[ERROR] 	at io.moia.streamee.demo.Main.main(Main.scala)
streamee-demo[ERROR] Caused by: java.lang.ClassNotFoundException: akka-dns
streamee-demo[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
streamee-demo[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
streamee-demo[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
streamee-demo[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
streamee-demo[ERROR] 	at java.lang.Class.forName0(Native Method)
streamee-demo[ERROR] 	at java.lang.Class.forName(Class.java:348)
streamee-demo[ERROR] 	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:22)
streamee-demo[ERROR] 	at scala.util.Try$.apply(Try.scala:209)
streamee-demo[ERROR] 	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:21)
streamee-demo[ERROR] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:39)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery$$anonfun$akka$discovery$ServiceDiscovery$$create$1$2.applyOrElse(ServiceDiscovery.scala:66)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery$$anonfun$akka$discovery$ServiceDiscovery$$create$1$2.applyOrElse(ServiceDiscovery.scala:64)
streamee-demo[ERROR] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
streamee-demo[ERROR] 	at scala.util.Failure.recoverWith(Try.scala:232)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery.akka$discovery$ServiceDiscovery$$create$1(ServiceDiscovery.scala:64)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery$$anonfun$2.applyOrElse(ServiceDiscovery.scala:74)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery$$anonfun$2.applyOrElse(ServiceDiscovery.scala:73)
streamee-demo[ERROR] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
streamee-demo[ERROR] 	at scala.util.Failure.recoverWith(Try.scala:232)
streamee-demo[ERROR] 	at akka.discovery.ServiceDiscovery.akka$discovery$ServiceDiscovery$$createServiceDiscovery(ServiceDiscovery.scala:73)
streamee-demo[ERROR] 	... 27 more
```

**Comment by aludwiko** [comment]
I have the same issue .

**Comment by gkocur** [comment]
Same here. With 0.16 works as expected.

**Comment by aludwiko** [comment]
Ok, in my case I was missing this line in the configuration:
```
io.dns.resolver = async-dns
```
and it is required by `DnsSimpleServiceDiscovery`:
```
  // Required for async dns
  AkkaVersion.require("discovery-dns", "2.5.14")
  require(system.settings.config.getString("akka.io.dns.resolver") == "async-dns",
    "Akka discovery DNS requires akka.io.dns.resolver to be set to async-dns")
```
Unfortunatelly, `ClassNotFoundException: akka-dns` could be a missleading message.

**Comment by hseeberger** [comment]
Gosh! And it is even documented here: https://developer.lightbend.com/docs/akka-management/current/discovery.html:

```
akka {
  discovery.method = akka-dns
  io.dns.resolver = async-dns
}
```
