### ISSUE TITLE
When when runing bootstrap-joining-demo-marathon-api-docker in marathon

### ISSUE THREAD

**Issue by ranglang** [akka/akka-management#249]
- HOSTNAME:  mesoslavea
- add i did use marathon-lb for port mapping

and when i try to start container, 

```
FO] [07/20/2018 15:28:21.583] [main] [akka.remote.Remoting] Starting remoting
[INFO] [07/20/2018 15:28:21.906] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://my-system@mesoslavea:31272]
[INFO] [07/20/2018 15:28:21.909] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://my-system@mesoslavea:31272]
[INFO] [07/20/2018 15:28:21.945] [main] [akka.cluster.Cluster(akka://my-system)] Cluster Node [akka.tcp://my-system@mesoslavea:31272] - Starting up...
[INFO] [07/20/2018 15:28:22.177] [main] [akka.cluster.Cluster(akka://my-system)] Cluster Node [akka.tcp://my-system@mesoslavea:31272] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [07/20/2018 15:28:22.177] [main] [akka.cluster.Cluster(akka://my-system)] Cluster Node [akka.tcp://my-system@mesoslavea:31272] - Started up successfully
[INFO] [07/20/2018 15:28:22.272] [my-system-akka.actor.default-dispatcher-7] [akka.cluster.Cluster(akka://my-system)] Cluster Node [akka.tcp://my-system@mesoslavea:31272] - No seed-nodes configured, manual cluster join required
[INFO] [07/20/2018 15:28:23.242] [main] [ClusterBootstrap(akka://my-system)] Bootstrap using default `akka.discovery` mechanism: MarathonApiSimpleServiceDiscovery
[INFO] [07/20/2018 15:28:23.276] [main] [AkkaManagement(akka://my-system)] Including HTTP management routes for ClusterHttpManagement
[INFO] [07/20/2018 15:28:23.346] [main] [AkkaManagement(akka://my-system)] Including HTTP management routes for ClusterBootstrap
[INFO] [07/20/2018 15:28:23.366] [main] [ClusterBootstrap(akka://my-system)] Got self contact point address: http://mesoslavea:31273
[INFO] [07/20/2018 15:28:23.397] [main] [AkkaManagement(akka://my-system)] Binding Akka Management (HTTP) endpoint to: 0.0.0.0:8558
[INFO] [07/20/2018 15:28:23.945] [main] [ClusterBootstrap(akka://my-system)] Initiating bootstrap procedure using akka.discovery method...
[INFO] [07/20/2018 15:28:23.987] [my-system-akka.actor.default-dispatcher-2] [akka.tcp://my-system@mesoslavea:31272/system/headlessServiceDnsBootstrap] Locating service members; Lookup: marathon-api-docker-app-label
[INFO] [07/20/2018 15:28:24.057] [my-system-akka.actor.default-dispatcher-17] [AkkaManagement(akka://my-system)] Bound Akka Management (HTTP) endpoint to: 0.0.0.0:8558
[ERROR] [07/20/2018 15:28:24.093] [my-system-akka.actor.default-dispatcher-6] [akka.tcp://my-system@mesoslavea:31272/system/IO-TCP/selectors/$a/1] Bind failed for TCP channel on endpoint [mesoslavea:31271]
java.net.SocketException: Unresolved address
	at sun.nio.ch.Net.translateToSocketException(Net.java:131)
	at sun.nio.ch.Net.translateException(Net.java:157)
	at sun.nio.ch.Net.translateException(Net.java:163)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:76)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)
	at akka.io.TcpListener.<init>(TcpListener.scala:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:65)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:563)
	at akka.actor.ActorCell.create(ActorCell.scala:589)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:218)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	... 20 more

[INFO] [07/20/2018 15:28:24.788] [my-system-akka.actor.default-dispatcher-4] [akka.tcp://my-system@mesoslavea:31272/system/headlessServiceDnsBootstrap] Discovered [1] observation, which is less than the required [2], retrying (interval: 1.000 s)
```

**Comment by ranglang** [comment]
any help would be appriciated
