### ISSUE TITLE
java.net.BindException: Cannot assign requested address

### ISSUE THREAD

**Issue by ranglang** [akka/akka-management#250]
while running docker marathon-api-docker in marathon, it throw an error of **java.net.BindException: Cannot assign requested address** 
```
[INFO] [07/20/2018 17:13:16.361] [main] [akka.remote.Remoting] Starting remoting
[INFO] [07/20/2018 17:13:17.018] [main] [akka.remote.Remoting] Remoting started; listening on addresses :[akka.tcp://my-system@47.98.172.1:31665]
[INFO] [07/20/2018 17:13:17.019] [main] [akka.remote.Remoting] Remoting now listens on addresses: [akka.tcp://my-system@47.98.172.1:31665]
[INFO] [07/20/2018 17:13:17.057] [main] [akka.cluster.Cluster(akka://my-system)] Cluster Node [akka.tcp://my-system@47.98.172.1:31665] - Starting up...
[INFO] [07/20/2018 17:13:17.451] [main] [akka.cluster.Cluster(akka://my-system)] Cluster Node [akka.tcp://my-system@47.98.172.1:31665] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [07/20/2018 17:13:17.451] [main] [akka.cluster.Cluster(akka://my-system)] Cluster Node [akka.tcp://my-system@47.98.172.1:31665] - Started up successfully
[INFO] [07/20/2018 17:13:17.656] [my-system-akka.actor.default-dispatcher-7] [akka.cluster.Cluster(akka://my-system)] Cluster Node [akka.tcp://my-system@47.98.172.1:31665] - No seed-nodes configured, manual cluster join required
[INFO] [07/20/2018 17:13:19.584] [main] [ClusterBootstrap(akka://my-system)] Bootstrap using default `akka.discovery` mechanism: MarathonApiSimpleServiceDiscovery
[INFO] [07/20/2018 17:13:19.668] [main] [AkkaManagement(akka://my-system)] Including HTTP management routes for ClusterHttpManagement
[INFO] [07/20/2018 17:13:19.798] [main] [AkkaManagement(akka://my-system)] Including HTTP management routes for ClusterBootstrap
[INFO] [07/20/2018 17:13:19.815] [main] [ClusterBootstrap(akka://my-system)] Got self contact point address: http://47.98.172.1:31666
[INFO] [07/20/2018 17:13:19.895] [main] [AkkaManagement(akka://my-system)] Binding Akka Management (HTTP) endpoint to: 0.0.0.0:8558
[INFO] [07/20/2018 17:13:21.067] [main] [ClusterBootstrap(akka://my-system)] Initiating bootstrap procedure using akka.discovery method...
[INFO] [07/20/2018 17:13:21.091] [my-system-akka.actor.default-dispatcher-4] [akka.tcp://my-system@47.98.172.1:31665/system/headlessServiceDnsBootstrap] Locating service members; Lookup: marathon-api-docker-app-label
[ERROR] [07/20/2018 17:13:21.227] [my-system-akka.actor.default-dispatcher-3] [akka.tcp://my-system@47.98.172.1:31665/system/IO-TCP/selectors/$a/1] Bind failed for TCP channel on endpoint [/47.98.172.1:31664]
java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)
	at akka.io.TcpListener.<init>(TcpListener.scala:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:65)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:563)
	at akka.actor.ActorCell.create(ActorCell.scala:589)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[INFO] [07/20/2018 17:13:21.255] [my-system-akka.actor.default-dispatcher-2] [AkkaManagement(akka://my-system)] Bound Akka Management (HTTP) 
```

**Comment by RatanRSur** [comment]
Hi, I'm seeing this error right now and I was wondering what you did to fix it

**Comment by raboof** [comment]
@RatanRSur the most common cause for this error is when the address is already in use. Are you running this application in a docker container? Are you using 'host networking' or 'bridge networking'?

**Comment by evollution** [comment]
HI , we have same issue and we use host networking for docker

**Comment by raboof** [comment]
this might be more suitable for a topic on https://discuss.akka.io .

In short, we recommend using 'bridge mode' because that allows each docker container to bind to the same port 'internally', instead of sharing and competing for the ports of the host.

If you must use 'host mode', you will have to configure each docker container to use unique ports, which will be painful.
