### ISSUE TITLE
Discovery Method: Aggregate multiple discovery mechanisms ClassNotFoundException

### ISSUE THREAD

**Issue by sebarys** [akka/akka-management#260]
Hello,

During attempt to use aggregate discovery method ( https://developer.lightbend.com/docs/akka-management/current/discovery.html#discovery-method-aggregate-multiple-discovery-mechanisms ) I am receiving Error:
```
[error] Exception in thread "main" java.lang.IllegalArgumentException: Illegal [akka.discovery.aggregate.class] value or incompatible class! The implementation class MUST extend akka.discovery.SimpleServiceDiscovery and take an ExtendedActorSystem as constructor argument.
[error] 	at akka.discovery.ServiceDiscovery$$anonfun$akka$discovery$ServiceDiscovery$$createServiceDiscovery$1.apply(ServiceDiscovery.scala:78)
[error] 	at akka.discovery.ServiceDiscovery$$anonfun$akka$discovery$ServiceDiscovery$$createServiceDiscovery$1.apply(ServiceDiscovery.scala:78)
[error] 	at scala.util.Try.getOrElse(Try.scala:79)
[error] 	at akka.discovery.ServiceDiscovery.akka$discovery$ServiceDiscovery$$createServiceDiscovery(ServiceDiscovery.scala:77)
[error] 	at akka.discovery.ServiceDiscovery$$anon$1.apply(ServiceDiscovery.scala:15)
[error] 	at akka.discovery.ServiceDiscovery$$anon$1.apply(ServiceDiscovery.scala:14)
[error] 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[error] 	at akka.discovery.ServiceDiscovery.loadServiceDiscovery(ServiceDiscovery.scala:46)
[error] 	at akka.discovery.ServiceDiscovery._simpleImpl$lzycompute(ServiceDiscovery.scala:28)
[error] 	at akka.discovery.ServiceDiscovery._simpleImpl(ServiceDiscovery.scala:28)
[error] 	at akka.discovery.ServiceDiscovery.discovery(ServiceDiscovery.scala:34)
[error] 	at akka.management.cluster.bootstrap.ClusterBootstrap.<init>(ClusterBootstrap.scala:46)
[error] 	at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:133)
[error] 	at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:127)
[error] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
[error] 	at akka.management.AkkaManagement$$anonfun$loadRouteProviders$1.apply(AkkaManagement.scala:192)
[error] 	at akka.management.AkkaManagement$$anonfun$loadRouteProviders$1.apply(AkkaManagement.scala:178)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.map(List.scala:296)
[error] 	at akka.management.AkkaManagement.loadRouteProviders(AkkaManagement.scala:178)
[error] 	at akka.management.AkkaManagement.<init>(AkkaManagement.scala:40)
[error] 	at akka.management.AkkaManagement$.createExtension(AkkaManagement.scala:30)
[error] 	at akka.management.AkkaManagement$.createExtension(AkkaManagement.scala:24)
[error] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
[error] 	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
[error] 	at akka.management.AkkaManagement$.apply(AkkaManagement.scala:24)
[error] 	at com.hybris.profile.lambdaengine.dispatcher.DispatcherApp$.delayedEndpoint$com$hybris$profile$lambdaengine$dispatcher$DispatcherApp$1(DispatcherApp.scala:45)
[error] 	at com.hybris.profile.lambdaengine.dispatcher.DispatcherApp$delayedInit$body.apply(DispatcherApp.scala:36)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at com.hybris.profile.lambdaengine.dispatcher.DispatcherApp$.main(DispatcherApp.scala:36)
[error] 	at com.hybris.profile.lambdaengine.dispatcher.DispatcherApp.main(DispatcherApp.scala)
[error] Caused by: java.lang.ClassNotFoundException: aggregate
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:22)
[error] 	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:21)
[error] 	at scala.util.Try$.apply(Try.scala:192)
[error] 	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:21)
[error] 	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:39)
[error] 	at akka.discovery.ServiceDiscovery$$anonfun$akka$discovery$ServiceDiscovery$$create$1$2.applyOrElse(ServiceDiscovery.scala:66)
[error] 	at akka.discovery.ServiceDiscovery$$anonfun$akka$discovery$ServiceDiscovery$$create$1$2.applyOrElse(ServiceDiscovery.scala:64)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[error] 	at scala.util.Failure.recoverWith(Try.scala:203)
[error] 	at akka.discovery.ServiceDiscovery.akka$discovery$ServiceDiscovery$$create$1(ServiceDiscovery.scala:64)
[error] 	at akka.discovery.ServiceDiscovery$$anonfun$2.applyOrElse(ServiceDiscovery.scala:74)
[error] 	at akka.discovery.ServiceDiscovery$$anonfun$2.applyOrElse(ServiceDiscovery.scala:73)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
[error] 	at scala.util.Failure.recoverWith(Try.scala:203)
[error] 	at akka.discovery.ServiceDiscovery.akka$discovery$ServiceDiscovery$$createServiceDiscovery(ServiceDiscovery.scala:73)
[error] 	... 36 more
```

I think that I have added all required dependencies to my build.sbt:
```
...
      "com.lightbend.akka.management" %% "akka-management-cluster-bootstrap" % "0.17.0",
      "com.lightbend.akka.discovery" %% "akka-discovery-aggregate" % "0.17.0",
      "com.lightbend.akka.discovery" %% "akka-discovery-config" % "0.17.0",
      "com.lightbend.akka.discovery" %% "akka-discovery-kubernetes-api" % "0.17.0",
...
```
and example configuration:
```
akka {
  management {
    http {
      hostname = "127.0.0.1"
      port = 8558
      bind-port = ${akka.management.http.port}
    }
    cluster.bootstrap {
      contact-point-discovery {
        service-name = "service1"
        required-contact-point-nr = 1
      }
      contact-point {
        fallback-port = 8558
      }
    }
  }
  discovery {
    method = aggregate
    aggregate {
      discovery-mechanisms = ["kubernetes-api", "config"]
    }

    config {
      services {
        service1 {
          endpoints = [
            {
              host = "127.0.0.1"
              port = 20000
            },
            {
              host = "127.0.0.1"
              port = 20100
            },
            {
              host = "127.0.0.1"
              port = 20200
            }
          ]
        }
      }
    }

    kubernetes-api {
      pod-namespace = "default"
      pod-namespace = ${?K8S_NAMESPACE}
      pod-label-selector = "app=%s"
      pod-label-selector = ${?K8S_SELECTOR}
      pod-port-name = "akka-mgmt-http"
      pod-port-name = ${?K8S_MANAGEMENT_PORT}
    }
  }
}
```

During my application startup I am receiving mentioned error. For discovery method `Configuration` it is working well.
Do you have any working example or someone could explain me where I am making mistake? 

**What I want to achieve:** 
If discovery based on kuberentes-api is possible use it, otherwise fallback to static configuration. It can be helpful for local developement:
- deploying to k8s cluster - `kubernetes-api` discovery mechanism is used, 
- running cluster locally - it is not kubernetes environment so fallback to static configuration is used

**Comment by chbatey** [comment]
Questions are better for the forum https://discuss.lightbend.com/c/akka

It looks like the aggregate jar hasn't made it on the classpath somehow.
