### ISSUE TITLE
Consul discovery incompatible class!

### ISSUE THREAD

**Issue by benniekrijger** [akka/akka-management#282]
When trying to use the akka-consul discovery method, i get an exception with the following stack trace:

```
[error] (run-main-0) java.lang.IllegalArgumentException: Illegal [akka.discovery.akka-consul.class] value or incompatible class! The implementation class MUST extend akka.discovery.SimpleServiceDiscovery and take an ExtendedActorSystem as constructor argument.
[error] java.lang.IllegalArgumentException: Illegal [akka.discovery.akka-consul.class] value or incompatible class! The implementation class MUST extend akka.discovery.SimpleServiceDiscovery and take an ExtendedActorSystem as constructor argument.
[error] 	at akka.discovery.ServiceDiscovery.$anonfun$createServiceDiscovery$1(ServiceDiscovery.scala:81)
[error] 	at scala.util.Failure.getOrElse(Try.scala:218)
[error] 	at akka.discovery.ServiceDiscovery.akka$discovery$ServiceDiscovery$$createServiceDiscovery(ServiceDiscovery.scala:78)
[error] 	at akka.discovery.ServiceDiscovery$$anon$1.apply(ServiceDiscovery.scala:15)
[error] 	at akka.discovery.ServiceDiscovery$$anon$1.apply(ServiceDiscovery.scala:14)
[error] 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[error] 	at akka.discovery.ServiceDiscovery.loadServiceDiscovery(ServiceDiscovery.scala:46)
[error] 	at akka.discovery.ServiceDiscovery._simpleImpl$lzycompute(ServiceDiscovery.scala:28)
[error] 	at akka.discovery.ServiceDiscovery._simpleImpl(ServiceDiscovery.scala:28)
[error] 	at akka.discovery.ServiceDiscovery.discovery(ServiceDiscovery.scala:34)
[error] 	at akka.management.cluster.bootstrap.ClusterBootstrap.<init>(ClusterBootstrap.scala:46)
[error] 	at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:133)
[error] 	at akka.management.cluster.bootstrap.ClusterBootstrap$.createExtension(ClusterBootstrap.scala:127)
[error] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
[error] 	at akka.management.AkkaManagement.$anonfun$loadRouteProviders$1(AkkaManagement.scala:192)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.immutable.List.map(List.scala:295)
[error] 	at akka.management.AkkaManagement.loadRouteProviders(AkkaManagement.scala:178)
[error] 	at akka.management.AkkaManagement.<init>(AkkaManagement.scala:40)
[error] 	at akka.management.AkkaManagement$.createExtension(AkkaManagement.scala:30)
[error] 	at akka.management.AkkaManagement$.createExtension(AkkaManagement.scala:24)
[error] 	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:913)
[error] 	at akka.actor.ExtensionId.apply(Extension.scala:79)
[error] 	at akka.actor.ExtensionId.apply$(Extension.scala:78)
[error] 	at akka.management.AkkaManagement$.apply(AkkaManagement.scala:24)
[error] 	at nl.blueflower.backend.Backend$.main(Backend.scala:104)
[error] 	at nl.blueflower.backend.Backend.main(Backend.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.ClassNotFoundException: akka-consul
[error] 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
```

Dependencies:
```
"com.lightbend.akka.management"       %% "akka-management-cluster-bootstrap"  % "0.17.0",
"com.lightbend.akka.discovery"        %% "akka-discovery-consul"              % "0.17.0",
```

Configuration (default):
```
akka.discovery {
  method = akka-consul
  akka-consul {

    #How to connect to Consul to fetch services data
    consul-host = "127.0.0.1"
    consul-port = 8500

    # Prefix for consul tag with the name of the actor system / application name,
    # services with this tag present will be found by the discovery mechanism
    # i.e. `system:test` will be found in cluster if the cluster system is named `test`
    application-name-tag-prefix = "system:"

    # Prefix for tag containing port number where akka management is set up so that
    # the seed nodes can be found, an example value for the tag would be `akka-management-port:19999`
    application-akka-management-port-tag-prefix = "akka-management-port:"
  }
}
```

Other methods like akka-dns and marathon-api work fine.

Seems related to #163

**Comment by benniekrijger** [comment]
Its was caused by a log4j2 configuration problem

**Comment by raboof** [comment]
Wow that's pretty obscure, thanks for reporting!

**Comment by GuntherW** [comment]
Having the same problem. (with 0.18.0)
What did you change to make it work?

**Comment by benniekrijger** [comment]
@GuntherW sorry for the late reply. I switched to the DNS discovery method, which uses the Consul DNS in turn.
