### ISSUE TITLE
bootstrap-dns won't form cluster

### ISSUE THREAD

**Issue by alanngai** [akka/akka-management#297]
This may be user error, but I'm having a difficult time getting cluster bootstrap to work with akka-dns discovery.

## Source
- [project](https://github.com/lightbend/es-demos-java/tree/master/drone-tracker)
- application configuration
  - [application.conf](https://github.com/lightbend/es-demos-java/blob/master/drone-tracker/conf/application.conf)
  - [application-dronesim.conf](https://github.com/lightbend/es-demos-java/blob/master/drone-tracker/conf/application-dronesim.conf)
- [k8s resource file](https://github.com/lightbend/es-demos-java/blob/master/drone-tracker/drone-sim.yaml)

## Environment Prereqs
- minikube is running
- docker environment is configured against minikube (via `eval $(minikube docker-env)`)
- es-console is installed (optional)

## Steps to Reproduce
1. from [project directory](https://github.com/lightbend/es-demos-java/tree/master/drone-tracker)
1. `mvn package docker:build`
1. `kubectl apply -f drone-sim.yaml`

## Expectation
Application cluster should spin up normally, verified via
- the [DroneSimCoordinator](https://github.com/lightbend/es-demos-java/blob/master/drone-tracker/app/dronesim/DroneSimCoordinator.java) actor, which is a cluster singleton, should spin up and log some messages.
- cinnamon/grafana graphs should show that cluster reach-ability for each node is 2 (cluster size)

## Actual behavior
- DroneSimCoordinator doesn't log any output
  - [logs-from-drone-sim-in-drone-sim-547b884bb9-hk9g2.txt](https://github.com/akka/akka-management/files/2378755/logs-from-drone-sim-in-drone-sim-547b884bb9-hk9g2.txt)
  - [logs-from-drone-sim-in-drone-sim-547b884bb9-4wbdj.txt](https://github.com/akka/akka-management/files/2378759/logs-from-drone-sim-in-drone-sim-547b884bb9-4wbdj.txt)
- node reach-ability graph is stuck at zero
![image](https://user-images.githubusercontent.com/1654394/45481769-424d1b80-b701-11e8-8836-eb9ab0457e27.png)

**Comment by alanngai** [comment]
I've been using the [bootstrap documentation](https://developer.lightbend.com/docs/akka-management/current/bootstrap.html) and this [sample project](https://github.com/akka/akka-management/tree/master/bootstrap-demo/kubernetes-dns) as a reference

**Comment by raboof** [comment]
(given this is more of a question rather than a bug/feature request it might have fit better on https://discuss.akka.io, but OK :) )

Looking at the logging I don't see `Initiating bootstrap procedure`. I think you need to call `AkkaManagement.get(system).start();` and `ClusterBootstrap.get(system).start();` to initialize Cluster Bootstrap. I don't see that in the project - might that be missing?

**Comment by alanngai** [comment]
thanks for the pointer about AkkaManagement.get().start(), etc., I was able to get a bit further.  Now I'm encountering an error on akka management startup

```	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
	at scala.concurrent.Promise.success(Promise.scala:82)
	at scala.concurrent.Promise.success$(Promise.scala:82)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:183)
	at akka.management.cluster.bootstrap.ClusterBootstrap.setSelfContactPoint(ClusterBootstrap.scala:108)
	at akka.management.cluster.bootstrap.ClusterBootstrap.routes(ClusterBootstrap.scala:69)
	at akka.management.AkkaManagement.$anonfun$prepareCombinedRoutes$3(AkkaManagement.scala:147)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at akka.management.AkkaManagement.prepareCombinedRoutes(AkkaManagement.scala:145)
	at akka.management.AkkaManagement.start(AkkaManagement.scala:98)
	at dronesim.Startup.&lt;init&gt;(Startup.java:35)
	at dronesim.Startup$$FastClassByGuice$$67d6522e.newInstance(&lt;generated&gt;)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
[info] a.m.c.b.ClusterBootstrap - Got self contact point address: http://172.17.0.10:8558```

**Comment by alanngai** [comment]
I’m wondering if this has something to do with this being a play app vs an akka app.  In the [kubernetes-dns example](https://github.com/akka/akka-management/blob/master/bootstrap-demo/kubernetes-dns/src/main/scala/akka/cluster/bootstrap/ClusterApp.scala), AkkaManagement is started before AkkaHttp is initialized.  In the case of my project, Play takes care of initializing AkkaHttp, so I'm not sure what effect that might have

**Comment by alanngai** [comment]
here's the part of the ClusterBootstrap code that throws

```
  /**
   * INTERNAL API
   *
   * Must be invoked by whoever starts the HTTP server with the `HttpClusterBootstrapRoutes`.
   * This allows us to "reverse lookup" from a lowest-address sorted contact point list,
   * that we discover via discovery, if a given contact point corresponds to our remoting address,
   * and if so, we may opt to join ourselves using the address.
   *
   * @return true if successfully set, false otherwise (i.e. was set already)
   */
  @InternalApi
  private[akka] def setSelfContactPoint(baseUri: Uri): Unit =
    _selfContactPointUri.success(baseUri)
```

**Comment by alanngai** [comment]
tagging @marcospereira to see if he has any insight

**Comment by alanngai** [comment]
After a lot of debugging and trying different things, out of desperation I did a `sbt clean` on the akka management project and a `mvn clean` on my projects and rebuilt everything from scratch.  Lo and behold, that fixed it.  That was no fun.
