### ISSUE TITLE
Failed: MultiDcSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#446]
```
[info] MultiDcSpec:
[info] Http cluster management
[info] - must allow multiple DCs *** FAILED *** (17 milliseconds)
[info]   java.net.BindException: Cannot assign requested address
[info]   at sun.nio.ch.Net.bind0(Native Method)
[info]   at sun.nio.ch.Net.bind(Net.java:433)
[info]   at sun.nio.ch.Net.bind(Net.java:425)
[info]   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
[info]   at akka.testkit.SocketUtil$$anonfun$temporaryServerAddresses$2.apply(SocketUtil.scala:93)
```

https://travis-ci.org/akka/akka-management/jobs/479754894

There was no other information in the logs in case travis removes the logs

**Comment by raboof** [comment]
Similar but not completely the same:

```
[info] MultiDcSpec:
[info] Http cluster management
[info] - must allow multiple DCs *** FAILED *** (581 milliseconds)
[info]   The future returned an exception of type: akka.stream.impl.io.ConnectionSourceStage$$anon$1$$anon$2, with message: Bind failed because of java.net.BindException: Address already in use. (MultiDcSpec.scala:67)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.management.cluster.MultiDcSpec.$anonfun$new$2(MultiDcSpec.scala:67)
```
