### ISSUE TITLE
Whitesource failues

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#447]
```
[info] Checking Policies for project akka-management-master in product Lightbend Reactive Platform
java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at org.whitesource.agent.api.ZipUtils.compress(ZipUtils.java:56)
	at org.whitesource.agent.client.WssServiceClientImpl.createHttpRequest(WssServiceClientImpl.java:291)
	at org.whitesource.agent.client.WssServiceClientImpl.service(WssServiceClientImpl.java:215)
```

https://travis-ci.org/akka/akka-management/jobs/479754383

**Comment by chbatey** [comment]
Looks like this is fixed in the latest white source client:
https://github.com/whitesource/agents/blob/master/wss-agent-utils/src/main/java/org/whitesource/agent/utils/ZipUtils.java
