### ISSUE TITLE
failed: LocalBootstrapTest

### ISSUE THREAD

**Issue by patriknw** [akka/akka-management#633]
```
[info] - should form a cluster *** FAILED *** (10 seconds, 73 milliseconds)
3702[info]   The code passed to eventually never returned normally. Attempted 19 times over 10.012518683 seconds. Last failure message: List(Up, Joining, Joining) did not equal List(Up, Up, Up). (LocalBootstrapTest.scala:110)
3703[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
3704[info]   at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
3705[info]   at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
3706[info]   at akka.management.LocalBootstrapTest.eventually(LocalBootstrapTest.scala:58)
3707[info]   at akka.management.LocalBootstrapTest$$anonfun$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(LocalBootstrapTest.scala:110)
3708[info]   at akka.management.LocalBootstrapTest$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(LocalBootstrapTest.scala:108)
3709[info]   at akka.management.LocalBootstrapTest$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(LocalBootstrapTest.scala:108)
```

**Comment by chbatey** [comment]
https://travis-ci.org/github/akka/akka-management/jobs/694200272#L6738
