### ISSUE TITLE
ClusterActorRefProvider does not define or inherit an implementation of the resolved method addressString()

### ISSUE THREAD

**Issue by arbitrary-dev** [akka/akka-management#640]
### Versions used 

Akka Management version: 1.0.5
Akka version: 2.6.3

### Expected Behavior

Working well

### Actual Behavior

```
Uncaught error from thread [akka-cluster-heartbeat-akka.actor.default-dispatcher-4]: Receiver class akka.cluster.ClusterActorRefProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String addressString()' of interface akka.actor.ActorRefProvider., shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[akka-cluster-heartbeat]
java.lang.AbstractMethodError: Receiver class akka.cluster.ClusterActorRefProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String addressString()' of interface akka.actor.ActorRefProvider.
	at akka.event.slf4j.Slf4jLogger.akka$event$slf4j$Slf4jLogger$$akkaAddress(Slf4jLogger.scala:63)
	at akka.event.slf4j.Slf4jLogger.withMdc(Slf4jLogger.scala:123)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:95)
	at akka.actor.Actor.aroundReceive(Actor.scala:534)
	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
	at akka.event.slf4j.Slf4jLogger.aroundReceive(Slf4jLogger.scala:55)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Uncaught error from thread [akka-cluster-heartbeat-akka.actor.default-dispatcher-7]: Receiver class akka.cluster.ClusterActorRefProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String addressString()' of interface akka.actor.ActorRefProvider., shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[akka-cluster-heartbeat]
java.lang.AbstractMethodError: Receiver class akka.cluster.ClusterActorRefProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String addressString()' of interface akka.actor.ActorRefProvider.
	at akka.event.slf4j.Slf4jLogger.akka$event$slf4j$Slf4jLogger$$akkaAddress(Slf4jLogger.scala:63)
	at akka.event.slf4j.Slf4jLogger.withMdc(Slf4jLogger.scala:123)
	at akka.event.slf4j.Slf4jLogger$$anonfun$receive$1.applyOrElse(Slf4jLogger.scala:69)
	at akka.actor.Actor.aroundReceive(Actor.scala:534)
	at akka.actor.Actor.aroundReceive$(Actor.scala:532)
```

**Comment by raboof** [comment]
Hm, this is certainly surprising. `ClusterActorRefProvider` extends `RemoteActorRefProvider` which implements this method.

The only way I could explain this is offhand if your akka-remote dependency is out of sync., though I would expect a more specific error in that case. Perhaps that error is not shown because this one prevents it?

**Comment by arbitrary-dev** [comment]
I guess the reason is `akka-management` [depends on Akka 2.5.27](https://github.com/akka/akka-management/blob/master/project/Dependencies.scala#L10) and that `ClusterActorRefProvider` lacks `addressString()`

**Comment by raboof** [comment]
I don't think so: because Akka is binary compatible between 2.5 and 2.6 (see https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html), using akka-management with Akka 2.6 (even though it was indeed built against 2.5) is supported.

Now of course it is possible a mistake was made there, but this is relatively unlikely as we use some tooling (https://github.com/lightbend/mima) and various automated tests to catch such problems.

On Akka 2.6.3, it is not a problem that `ClusterActorRefProvider` lacks `addressString()` itself, because there `RemoteActorRefProvider` has `addressString()`, and `ClusterActorRefProvider` extends `RemoteActorRefProvider`.

However, on earlier versions of Akka, `RemoteActorRefProvider` did not contain `addressString`. For that reason I suspect you are using an older version of akka-remote, while you use a recent version of akka-actor and/of akka-slf4j.

While it is fine to use akka-management with either Akka 2.5.27 or Akka 2.6.3, you cannot 'mix' versions of the core artifacts: if you're using version 2.6.3 of akka-actor and akka-slf4j, you must also use version 2.6.3 of akka-remote.

**Comment by arbitrary-dev** [comment]
Ok, then probably I should specify dependencies more explicitly in my project. Thanks for clarification!

**Comment by raboof** [comment]
:+1:
