### ISSUE TITLE
Cluster Bootstrap (config mode) does not work with IPv6 endpoints

### ISSUE THREAD

**Issue by djm1329** [akka/akka-management#657]
### Versions used 

Akka version: 2.6.4
Akka Management version: 1.0.6

### Expected Behavior

Configuring Akka Discovery with an endpoint at `akka.discovery.config.services.<service-name>.endpoints` using an IPv6 address for host should work as far as I understand. 

### Actual Behavior

Instead, an exception is thrown causing failure of the BootstrapCoordinator and no cluster is formed. 

### Relevant logs

```
2020-04-10 14:26:10,183 ERROR OneForOneStrategy akka://ccs-cluster/system/bootstrapCoordinator ccs-cluster-akka.actor.internal-dispatcher-3 - Invalid actor path element [contactPointProbe-[fe80::1013:2070:258a:c662]-9231], illegal character [[] at position: 18. Actor paths MUST: not start with `$`, include only ASCII letters and can only contain these special characters: -_.*$+:@&=,!~';.
akka.actor.InvalidActorNameException: Invalid actor path element [contactPointProbe-[fe80::1013:2070:258a:c662]-9231], illegal character [[] at position: 18. Actor paths MUST: not start with `$`, include only ASCII letters and can only contain these special characters: -_.*$+:@&=,!~';.
	at akka.actor.ActorPath$.validatePathElement(ActorPath.scala:98)
	at akka.actor.ActorPath$.validatePathElement(ActorPath.scala:76)
	at akka.actor.dungeon.Children.checkName(Children.scala:248)
	at akka.actor.dungeon.Children.actorOf(Children.scala:47)
	at akka.actor.dungeon.Children.actorOf$(Children.scala:46)
	at akka.actor.ActorCell.actorOf(ActorCell.scala:408)
	at akka.management.cluster.bootstrap.internal.BootstrapCoordinator.ensureProbing(BootstrapCoordinator.scala:380)
	at akka.management.cluster.bootstrap.internal.BootstrapCoordinator.$anonfun$onContactPointsResolved$2(BootstrapCoordinator.scala:345)
```

The problem appears to be with the name created for a child of the BootstrapCoordinator actor used to support the bootstrap process. The actor name is formed from the IP address and port, and when the address is IPv6 it results in attempting to use a string containing "[" as the actor name.

**Comment by ennru** [comment]
Fixed with #658
