### ISSUE TITLE
Failed: KubernetesApiIntegrationTest: Kubernetes lease resource should be able to be created

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#695]
```
[info] KubernetesApiSpec:
[info] Kubernetes lease resource
[info] - should be able to be created *** FAILED *** (3 seconds, 530 milliseconds)
[info]   The future returned an exception of type: akka.coordination.lease.LeaseTimeoutException, with message: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?. (KubernetesApiSpec.scala:81)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
```

```
[info] - should renew time if lease is owned by client on initial acquire (166 milliseconds)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[WARN] [06/09/2020 11:03:06.412] [local-cluster-akka.actor.default-dispatcher-7] [akka.cluster.Cluster(akka://local-cluster)] Cluster Node [akka://local-cluster@localhost:44919] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [2728] ms ago, expected interval is [1000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
[WARN] [06/09/2020 11:03:06.416] [local-cluster-akka.actor.default-dispatcher-3] [akka.cluster.Cluster(akka://local-cluster)] Cluster Node [akka://local-cluster@localhost:34609] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [2629] ms ago, expected interval is [1000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
[WARN] [06/09/2020 11:03:06.418] [local-cluster-akka.actor.default-dispatcher-6] [akka.cluster.Cluster(akka://local-cluster)] Cluster Node [akka://local-cluster@localhost:45523] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [2084] ms ago, expected interval is [1000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
[WARN] [06/09/2020 11:03:06.432] [local-cluster-akka.actor.default-dispatcher-17] [akka.cluster.Cluster(akka://local-cluster)] Cluster Node [akka://local-cluster@localhost:44149] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [2211] ms ago, expected interval is [1000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
[WARN] [06/09/2020 11:03:06.433] [local-cluster-akka.actor.default-dispatcher-18] [akka.cluster.Cluster(akka://local-cluster)] Cluster Node [akka://local-cluster@localhost:39717] - Scheduled sending of heartbeat was delayed. Previous heartbeat was sent [2443] ms ago, expected interval is [1000] ms. This may cause failure detection to mark members as unreachable. The reason can be thread starvation, e.g. by running blocking tasks on the default dispatcher, CPU overload, or GC.
[WARN] [06/09/2020 11:03:06.437] [local-cluster-akka.actor.default-dispatcher-5] [akka.remote.PhiAccrualFailureDetector@1fe5d2e1] heartbeat interval is growing too large for address akka://local-cluster@localhost:44149: 2648 millis
[WARN] [06/09/2020 11:03:06.443] [local-cluster-akka.actor.default-dispatcher-2] [akka.remote.PhiAccrualFailureDetector@26305a9d] heartbeat interval is growing too large for address akka://local-cluster@localhost:44919: 2108 millis
[WARN] [06/09/2020 11:03:06.443] [local-cluster-akka.actor.default-dispatcher-3] [akka.remote.PhiAccrualFailureDetector@6aa632c8] heartbeat interval is growing too large for address akka://local-cluster@localhost:45523: 2755 millis
[WARN] [06/09/2020 11:03:06.444] [local-cluster-akka.actor.default-dispatcher-10] [akka.remote.PhiAccrualFailureDetector@238eda60] heartbeat interval is growing too large for address akka://local-cluster@localhost:34609: 2227 millis
[WARN] [06/09/2020 11:03:06.447] [local-cluster-akka.actor.default-dispatcher-12] [akka.remote.PhiAccrualFailureDetector@464b711b] heartbeat interval is growing too large for address akka://local-cluster@localhost:41377: 2657 millis
[WARN] [06/09/2020 11:03:06.458] [local-cluster-akka.actor.default-dispatcher-3] [akka.remote.PhiAccrualFailureDetector@42f1f40b] heartbeat interval is growing too large for address akka://local-cluster@localhost:39717: 2770 millis
[WARN] [06/09/2020 11:03:06.461] [local-cluster-akka.actor.default-dispatcher-5] [akka.remote.PhiAccrualFailureDetector@658cb05a] heartbeat interval is growing too large for address akka://local-cluster@localhost:39717: 2121 millis
[WARN] [06/09/2020 11:03:06.462] [local-cluster-akka.actor.default-dispatcher-18] [akka.remote.PhiAccrualFailureDetector@74e3b4e] heartbeat interval is growing too large for address akka://local-cluster@localhost:44919: 2470 millis
[WARN] [06/09/2020 11:03:06.462] [local-cluster-akka.actor.default-dispatcher-2] [akka.remote.PhiAccrualFailureDetector@267da0cc] heartbeat interval is growing too large for address akka://local-cluster@localhost:45523: 2471 millis
[WARN] [06/09/2020 11:03:06.471] [local-cluster-akka.actor.default-dispatcher-9] [akka.remote.PhiAccrualFailureDetector@7c707b75] heartbeat interval is growing too large for address akka://local-cluster@localhost:41377: 2229 millis
[WARN] [06/09/2020 11:03:07.767] [KubernetesApiSpec-akka.actor.default-dispatcher-16] [KubernetesApiSpec/Pool(shared->http://localhost:32933)] [0 (WaitingForResponseEntitySubscription)] Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. DELETE /apis/akka.io/v1/namespaces/lease/leases/lease-1 Empty -> 404 Not Found Chunked
[ERROR] [06/09/2020 11:03:07.787] [KubernetesApiSpec-akka.actor.default-dispatcher-16] [akka.actor.ActorSystemImpl(KubernetesApiSpec)] Outgoing request stream error
java.util.concurrent.TimeoutException: Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. DELETE /apis/akka.io/v1/namespaces/lease/leases/lease-1 Empty -> 404 Not Found Chunked
	at akka.http.impl.engine.client.pool.SlotState$WaitingForResponseEntitySubscription.onTimeout(SlotState.scala:317)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onTimeout$1(NewHostConnectionPool.scala:169)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:171)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:259)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:341)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:350)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:249)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.$anonfun$updateState$1(NewHostConnectionPool.scala:270)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1(NewHostConnectionPool.scala:597)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1$adapted(NewHostConnectionPool.scala:597)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:452)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:481)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[WARN] [06/09/2020 11:03:07.893] [KubernetesApiSpec-akka.actor.default-dispatcher-4] [KubernetesApiSpec/Pool(shared->http://localhost:32933)] [1 (WaitingForResponseEntitySubscription)] Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. PUT /apis/akka.io/v1/namespaces/lease/leases/lease-1 Strict(142 bytes) -> 409 Conflict Chunked
[ERROR] [06/09/2020 11:03:07.894] [KubernetesApiSpec-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(KubernetesApiSpec)] Outgoing request stream error
java.util.concurrent.TimeoutException: Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. PUT /apis/akka.io/v1/namespaces/lease/leases/lease-1 Strict(142 bytes) -> 409 Conflict Chunked
	at akka.http.impl.engine.client.pool.SlotState$WaitingForResponseEntitySubscription.onTimeout(SlotState.scala:317)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onTimeout$1(NewHostConnectionPool.scala:169)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:171)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:259)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:341)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:350)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:249)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.$anonfun$updateState$1(NewHostConnectionPool.scala:270)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1(NewHostConnectionPool.scala:597)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1$adapted(NewHostConnectionPool.scala:597)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:452)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:481)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[INFO] [06/09/2020 11:03:07.896] [KubernetesApiSpec-akka.actor.default-dispatcher-16] [KubernetesApiImpl(akka://KubernetesApiSpec)] lease lease-1 does not exist, creating
[WARN] [06/09/2020 11:03:09.594] [KubernetesApiSpec-akka.actor.default-dispatcher-2] [KubernetesApiSpec/Pool(shared->http://localhost:32933)] [2 (WaitingForResponseEntitySubscription)] Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. GET /apis/akka.io/v1/namespaces/lease/leases/lease-1 Empty -> 200 OK Chunked
[ERROR] [06/09/2020 11:03:09.595] [KubernetesApiSpec-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(KubernetesApiSpec)] Outgoing request stream error
java.util.concurrent.TimeoutException: Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. GET /apis/akka.io/v1/namespaces/lease/leases/lease-1 Empty -> 200 OK Chunked
	at akka.http.impl.engine.client.pool.SlotState$WaitingForResponseEntitySubscription.onTimeout(SlotState.scala:317)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onTimeout$1(NewHostConnectionPool.scala:169)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:171)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:259)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:341)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:350)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:249)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.$anonfun$updateState$1(NewHostConnectionPool.scala:270)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1(NewHostConnectionPool.scala:597)
	at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1$adapted(NewHostConnectionPool.scala:597)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:452)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:481)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[WARN] [06/09/2020 11:03:10.451] [KubernetesApiSpec-akka.actor.default-dispatcher-3] [KubernetesApiSpec/Pool(shared->http://localhost:32933)] [0 (WaitingForResponseEntitySubscription)] Ongoing request [POST /apis/akka.io/v1/namespaces/lease/leases/lease-1 Strict(113 bytes)] was dropped because pool is shutting down
[WARN] [06/09/2020 11:03:10.452] [KubernetesApiSpec-akka.actor.default-dispatcher-3] [KubernetesApiSpec/Pool(shared->http://localhost:32933)] [1 (WaitingForResponseEntitySubscription)] Ongoing request [PUT /apis/akka.io/v1/namespaces/lease/leases/lease-1 Strict(141 bytes)] was dropped because pool is shutting down
[WARN] [06/09/2020 11:03:10.452] [KubernetesApiSpec-akka.actor.default-dispatcher-3] [KubernetesApiSpec/Pool(shared->http://localhost:32933)] [2 (WaitingForResponse)] Ongoing request [DELETE /apis/akka.io/v1/namespaces/lease/leases/lease-1 Empty] was dropped because pool is shutting down
[info] KubernetesApiSpec:
```

Also looks like we don't discard entity bytes if a request times out

**Comment by jchapuis** [comment]
I think that we might have run into this very same issue in production, here's our log:

```
level: ERROR
level_value: 40000
logger_name: akka.actor.ActorSystemImpl
message: Outgoing request stream error
num_hits: 4
num_matches: 2
port: 43476
stack_trace: java.util.concurrent.TimeoutException: Response entity was not subscribed after 1 second. Make sure to read the response entity body or call discardBytes() on it. GET /api/v1/namespaces/qa/pods Empty -> 200 OK Chunked
    at akka.http.impl.engine.client.pool.SlotState$WaitingForResponseEntitySubscription.onTimeout(SlotState.scala:317)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$onTimeout$1(NewHostConnectionPool.scala:169)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Event$.$anonfun$event0$1(NewHostConnectionPool.scala:171)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:259)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:341)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:350)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:249)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.$anonfun$updateState$1(NewHostConnectionPool.scala:270)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1(NewHostConnectionPool.scala:597)
    at akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.$anonfun$safeCallback$1$adapted(NewHostConnectionPool.scala:597)
    at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:466)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:497)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:599)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:768)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:783)
    at akka.actor.Actor.aroundReceive(Actor.scala:534)
    at akka.actor.Actor.aroundReceive$(Actor.scala:532)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:690)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
    at akka.actor.ActorCell.invoke(ActorCell.scala:543)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
    at akka.dispatch.Mailbox.run(Mailbox.scala:230)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
type: logback
```

**Comment by chbatey** [comment]
Hi @jchapuis this isn't the same issue, that is when getting a list of pods, this issue is for a test of a class used by the Kubernetes Lease.

Feel free to create a separate issue for yours, with some surrounding logs as well. It could be your pod was starved of CPU so the request wasn't read in time.

**Comment by ennru** [comment]
https://travis-ci.org/github/akka/akka-management/jobs/715410726#L2959

**Comment by ennru** [comment]
https://travis-ci.org/github/akka/akka-management/jobs/729599610#L1154

**Comment by seglo** [comment]
https://travis-ci.com/github/akka/akka-management/jobs/448641878#L657

**Comment by chbatey** [comment]
Fixed by https://github.com/akka/akka-management/pull/822
