### ISSUE TITLE
Akka Cluster doesn't come up due to mixed version of artifacts

### ISSUE THREAD

**Issue by kessiler** [akka/akka-management#754]
### Versions used 

Akka HTTP: 10.2.0
Akka Management: 1.0.8
Akka version: 2.6.8

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.
Akka Cluster to start using the latest version of Akka and Akka HTTP.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.
Akka Cluster doesn't start due to Akka Management bringing mixed version of artifacts.

```
Caused by: java.lang.IllegalStateException: You are using version 10.2.0 of Akka HTTP, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 10.2.0 of the [akka-http-spray-json] artifacts to your project. See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed

```

### Relevant logs

If you identified a section in your logs that explains the bug or might be important to understand it, please add it.

```
Caused by: java.lang.IllegalStateException: You are using version 10.2.0 of Akka HTTP, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 10.2.0 of the [akka-http-spray-json] artifacts to your project. See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
	at akka.util.ManifestInfo.checkSameVersion(ManifestInfo.scala:217)
	at akka.util.ManifestInfo.checkSameVersion(ManifestInfo.scala:195)
	at akka.http.scaladsl.HttpExt.<init>(Http.scala:79)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:1080)
	at akka.http.scaladsl.Http$.createExtension(Http.scala:814)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1145)
	at akka.actor.ExtensionId.apply(Extension.scala:78)
	at akka.actor.ExtensionId.apply$(Extension.scala:77)
	at akka.http.scaladsl.Http$.apply(Http.scala:1075)
	at akka.management.scaladsl.AkkaManagement.$anonfun$start$2(AkkaManagement.scala:146)
	at scala.Option.getOrElse(Option.scala:201)
	at akka.management.scaladsl.AkkaManagement.start(AkkaManagement.scala:146)
	at akka.management.scaladsl.AkkaManagement.start(AkkaManagement.scala:116)
	at akka.management.javadsl.AkkaManagement.start(AkkaManagement.scala:64)
	at com.tenfold.lib.akka.cluster.ClusterService.startClusterManagement(ClusterService.java:49)
	at com.tenfold.lib.akka.cluster.ClusterService.lambda$initializeActorSystem$b20b5607$1(ClusterService.java:27)
	at akka.actor.typed.javadsl.Behaviors$.$anonfun$setup$1(Behaviors.scala:47)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:119)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.internal.InterceptorImpl$$anon$1.start(InterceptorImpl.scala:50)
	at akka.actor.typed.BehaviorInterceptor.aroundStart(BehaviorInterceptor.scala:55)
	at akka.actor.typed.internal.InterceptorImpl.preStart(InterceptorImpl.scala:73)
	at akka.actor.typed.internal.InterceptorImpl$.$anonfun$apply$1(InterceptorImpl.scala:30)
	at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:119)
	at akka.actor.typed.Behavior$.start(Behavior.scala:168)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:275)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:129)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:106)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
```

### Reproducible Test Case

Simply create a new project with following dependencies:

```
ext {
    akkaManagement = "1.0.8"
    akkaVersion = "2.6.8"
    scalaBinary = "2.13"
}

dependencies {
    implementation('ch.qos.logback:logback-classic:1.2.3')
    implementation group: 'com.typesafe.akka',
            name: "akka-cluster-typed_${scalaBinary}", version: "${akkaVersion}"
    implementation group: 'com.typesafe.akka',
        name: "akka-cluster-tools_${scalaBinary}", version: "${akkaVersion}"
    implementation group: 'com.typesafe.akka',
        name: "akka-cluster-sharding_${scalaBinary}", version: "${akkaVersion}"
    implementation group: 'com.typesafe.akka',
        name: "akka-discovery_${scalaBinary}", version: "${akkaVersion}"
    implementation group: 'com.lightbend.akka.management',
            name: "akka-management-cluster-bootstrap_${scalaBinary}", version: "${akkaManagement}"
    implementation group: 'com.lightbend.akka.management',
        name: "akka-management-cluster-http_${scalaBinary}", version: "${akkaManagement}"
}
```

**Comment by kessiler** [comment]
Current workaround: Force Gradle resolution to the new version of Akka HTTP Spray JSON

https://mvnrepository.com/artifact/com.typesafe.akka/akka-http-spray-json_2.13/10.2.0

`compile group: 'com.typesafe.akka', name: 'akka-http-spray-json_2.13', version: '10.2.0'
`

**Comment by patriknw** [comment]
That is expected behavior and the error message is clear.
