### ISSUE TITLE
Failed: ErrImageNeverPull in integration tests

### ISSUE THREAD

**Issue by seglo** [akka/akka-management#767]
Looks like it's caused by an image publish error

```
[error] java.lang.RuntimeException: Nonzero exit value: 1
[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:631)
[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.$anonfun$projectSettings$49(DockerPlugin.scala:247)
[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.$anonfun$projectSettings$49$adapted(DockerPlugin.scala:239)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

Symptom later on, container can't be pulled:

```
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ContainerCreating   0          0s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ContainerCreating   0          0s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ContainerCreating   0          0s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          4s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          4s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          4s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          9s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          9s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          9s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          13s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          13s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          13s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          17s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          17s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          17s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          21s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          21s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          21s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          25s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          25s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          25s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          30s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          30s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          30s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          34s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          34s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          34s
Waiting for pods to get ready...
NAME                                   READY   STATUS              RESTARTS   AGE
akka-bootstrap-demo-7d84d74778-8wz5t   0/1     ErrImageNeverPull   0          38s
akka-bootstrap-demo-7d84d74778-fdk6t   0/1     ErrImageNeverPull   0          38s
akka-bootstrap-demo-7d84d74778-x66jw   0/1     ErrImageNeverPull   0          38s
Pods did not get ready
The command "./scripts/setup-minikube-for-linux.sh && ./integration-test/kubernetes-api/test.sh" exited with 255.
```
https://travis-ci.org/github/akka/akka-management/jobs/727993083#L523

**Comment by chbatey** [comment]
This was an error pulling the openjdk image. We have only seen it once. Let's close this but make the script bail out if any step  fails
