### ISSUE TITLE
Failed: KubernetesApiSpec => LeaseTimeoutException, with message: Timed out removing lease [lease-1]

### ISSUE THREAD

**Issue by octonato** [akka/akka-management#768]
https://travis-ci.org/github/akka/akka-management/jobs/728309081#L1161

```scala
[info] - should be able to be created *** FAILED *** (2 seconds, 39 milliseconds)
[info]   The future returned an exception of type: akka.coordination.lease.LeaseTimeoutException, with message: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?. (KubernetesApiSpec.scala:83)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.coordination.lease.kubernetes.KubernetesApiSpec.$anonfun$new$2(KubernetesApiSpec.scala:83)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)

```

**Comment by raboof** [comment]
https://travis-ci.org/github/akka/akka-management/jobs/733642654

**Comment by ennru** [comment]
https://travis-ci.org/github/akka/akka-management/jobs/737041013#L5456 in #787

**Comment by ennru** [comment]
https://travis-ci.org/github/akka/akka-management/jobs/724899784#L5453 in #758

**Comment by jrudolph** [comment]
https://travis-ci.com/github/akka/akka-management/jobs/430671890

but there also were a few other kinds of failures in that test:

```
[info] KubernetesApiIntegrationTest:

[info] Kubernetes lease resource

[info] - should be able to be created *** FAILED ***

[info]   The future returned an exception of type: akka.coordination.lease.LeaseTimeoutException, with message: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?. (KubernetesApiIntegrationTest.scala:56)

[info] - should be able to read back with same version *** FAILED ***

[info]   "[586]" did not equal "[]" (KubernetesApiIntegrationTest.scala:66)

[info]   Analysis:

[info]   "[586]" -> "[]"

[info] - should be able to take a lease with no owner *** FAILED ***

[info]   The future returned an exception of type: akka.coordination.lease.LeaseException, with message: PUT for lease lease-1 returned unexpected status code 422 Unprocessable Entity. Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"leases.akka.io \"lease-1\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update","reason":"Invalid","details":{"name":"lease-1","group":"akka.io","kind":"leases","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: 0x0: must be specified for an update","field":"metadata.resourceVersion"}]},"code":422}

[info]   . (KubernetesApiIntegrationTest.scala:70)

[info] - should be able to update a lease if resource version is correct *** FAILED ***

[info]   The future returned an exception of type: akka.coordination.lease.LeaseException, with message: PUT for lease lease-1 returned unexpected status code 422 Unprocessable Entity. Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"leases.akka.io \"lease-1\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update","reason":"Invalid","details":{"name":"lease-1","group":"akka.io","kind":"leases","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: 0x0: must be specified for an update","field":"metadata.resourceVersion"}]},"code":422}

[info]   . (KubernetesApiIntegrationTest.scala:81)

[info] - should not be able to update a lease if resource version is correct *** FAILED ***

[info]   "[586]" did not equal "[]" (KubernetesApiIntegrationTest.scala:97)

[info]   Analysis:

[info]   "[586]" -> "[]"

[info] - should be able to remove ownership *** FAILED ***

[info]   The future returned an exception of type: akka.coordination.lease.LeaseException, with message: PUT for lease lease-1 returned unexpected status code 422 Unprocessable Entity. Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"leases.akka.io \"lease-1\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update","reason":"Invalid","details":{"name":"lease-1","group":"akka.io","kind":"leases","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: 0x0: must be specified for an update","field":"metadata.resourceVersion"}]},"code":422}

[info]   . (KubernetesApiIntegrationTest.scala:104)

[info] - should be able to get lease once other client has removed *** FAILED ***

[info]   The future returned an exception of type: akka.coordination.lease.LeaseException, with message: PUT for lease lease-1 returned unexpected status code 422 Unprocessable Entity. Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"leases.akka.io \"lease-1\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update","reason":"Invalid","details":{"name":"lease-1","group":"akka.io","kind":"leases","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: 0x0: must be specified for an update","field":"metadata.resourceVersion"}]},"code":422}

[info]   . (KubernetesApiIntegrationTest.scala:114)
```

**Comment by johanandren** [comment]
https://travis-ci.com/github/akka/akka-management/jobs/439864834

This time no other fails

**Comment by johanandren** [comment]
https://travis-ci.com/github/akka/akka-management/jobs/440130876
