### ISSUE TITLE
[Failed] LocalBootstrapTest

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-management#771]
refs #633 

https://travis-ci.org/github/akka/akka-management/jobs/729288906

<details>
<summary>output snippet</summary>

```
[info] LocalBootstrapTest:

[info] Cluster bootstrap with health checks

[info] - should not be ready initially *** FAILED *** (20 seconds, 547 milliseconds)

[info]   The code passed to eventually never returned normally. Attempted 21 times over 20.530426862 seconds. Last failure message: The future returned an exception of type: akka.stream.StreamTcpException, with message: The connection closed with error: Connection reset by peer.. (LocalBootstrapTest.scala:95)

[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:

[info]   at org.scalatest.enablers.Retrying$$anon$4.tryTryAgain$2(Retrying.scala:185)

[info]   at org.scalatest.enablers.Retrying$$anon$4.retry(Retrying.scala:192)

[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:402)

[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:401)

[info]   at akka.management.LocalBootstrapTest.eventually(LocalBootstrapTest.scala:59)

[info]   at akka.management.LocalBootstrapTest.$anonfun$new$5(LocalBootstrapTest.scala:95)

[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)

[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)

[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)

[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)

[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)

[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)

[info]   at org.scalatest.wordspec.AnyWordSpec.withFixture(AnyWordSpec.scala:1879)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)

[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)

[info]   at org.scalatest.wordspec.AnyWordSpec.runTest(AnyWordSpec.scala:1879)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)

[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)

[info]   at scala.collection.immutable.List.foreach(List.scala:392)

[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)

[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)

[info]   at scala.collection.immutable.List.foreach(List.scala:392)

[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)

[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)

[info]   at org.scalatest.wordspec.AnyWordSpec.runTests(AnyWordSpec.scala:1879)

[info]   at org.scalatest.Suite.run(Suite.scala:1112)

[info]   at org.scalatest.Suite.run$(Suite.scala:1094)

[info]   at org.scalatest.wordspec.AnyWordSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AnyWordSpec.scala:1879)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)

[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)

[info]   at org.scalatest.wordspec.AnyWordSpec.run(AnyWordSpec.scala:1879)

[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)

[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)

[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:139)

[info]   at sbt.TestRunner.run(TestFramework.scala:154)

[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:317)

[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:277)

[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)

[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)

[info]   at sbt.TestFunction.apply(TestFramework.scala:329)

[info]   at sbt.Tests$.processRunnable$1(Tests.scala:350)

[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:356)

[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)

[info]   at sbt.std.Transform$$anon$4.work(Transform.scala:67)

[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:281)

[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)

[info]   at sbt.Execute.work(Execute.scala:290)

[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:281)

[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)

[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)

[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[info]   at java.lang.Thread.run(Thread.java:748)

[info]   Cause: org.scalatest.exceptions.TestFailedException: The future returned an exception of type: akka.stream.StreamTcpException, with message: The connection closed with error: Connection reset by peer.

[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)

[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)

[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)

[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)

[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)

[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)

[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)

[info]   at akka.management.LocalBootstrapTest.healthCheckStatus(LocalBootstrapTest.scala:84)

[info]   at akka.management.LocalBootstrapTest.readyStatusCode(LocalBootstrapTest.scala:77)

[info]   at akka.management.LocalBootstrapTest.$anonfun$new$7(LocalBootstrapTest.scala:97)

[info]   at akka.management.LocalBootstrapTest.$anonfun$new$7$adapted(LocalBootstrapTest.scala:96)

[info]   at scala.collection.Iterator.foreach(Iterator.scala:943)

[info]   at scala.collection.Iterator.foreach$(Iterator.scala:943)

[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:74)

[info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)

[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
...
```

</details>

**Comment by chbatey** [comment]
hah, artery picked the same port as the random port selection for management

**Comment by ignasi35** [comment]
Again in https://travis-ci.com/github/akka/akka-management/jobs/489782209
