### ISSUE TITLE
Failed: ClusterBootstrapIntegrationSpec should join three DNS discovered nodes by forming new cluster (happy path)

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-management#785]
https://travis-ci.org/github/akka/akka-management/jobs/735368957

```
[info] Cluster Bootstrap

[info] - should join three DNS discovered nodes by forming new cluster (happy path) *** FAILED *** (30 seconds, 46 milliseconds)

[info]   java.lang.AssertionError: assertion failed: timeout (30 seconds) during expectMsgClass waiting for class akka.cluster.ClusterEvent$MemberUp

[info]   at scala.Predef$.assert(Predef.scala:282)

[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:569)

[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:551)

[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:550)

[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:969)

[info]   at akka.management.cluster.bootstrap.contactpoint.ClusterBootstrapIntegrationSpec.$anonfun$new$5(ClusterBootstrapIntegrationSpec.scala:145)

[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)

[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)

[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)

[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)

[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)

[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)

[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)

[info]   at akka.management.cluster.bootstrap.contactpoint.ClusterBootstrapIntegrationSpec.withFixture(ClusterBootstrapIntegrationSpec.scala:25)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)

[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)

[info]   at akka.management.cluster.bootstrap.contactpoint.ClusterBootstrapIntegrationSpec.runTest(ClusterBootstrapIntegrationSpec.scala:25)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)

[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)

[info]   at scala.collection.immutable.List.foreach(List.scala:333)

[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)

[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)

[info]   at scala.collection.immutable.List.foreach(List.scala:333)

[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)

[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)

[info]   at akka.management.cluster.bootstrap.contactpoint.ClusterBootstrapIntegrationSpec.runTests(ClusterBootstrapIntegrationSpec.scala:25)

[info]   at org.scalatest.Suite.run(Suite.scala:1112)

[info]   at org.scalatest.Suite.run$(Suite.scala:1094)

[info]   at akka.management.cluster.bootstrap.contactpoint.ClusterBootstrapIntegrationSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(ClusterBootstrapIntegrationSpec.scala:25)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)

[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)

[info]   at akka.management.cluster.bootstrap.contactpoint.ClusterBootstrapIntegrationSpec.run(ClusterBootstrapIntegrationSpec.scala:25)

[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)

[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)

[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:139)

[info]   at sbt.TestRunner.run(TestFramework.scala:154)

[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:317)

[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:277)

[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)

[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)

[info]   at sbt.TestFunction.apply(TestFramework.scala:329)

[info]   at sbt.Tests$.processRunnable$1(Tests.scala:350)

[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:356)

[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)

[info]   at sbt.std.Transform$$anon$4.work(Transform.scala:67)

[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:281)

[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)

[info]   at sbt.Execute.work(Execute.scala:290)

[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:281)

[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)

[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)

[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by chbatey** [comment]
The test has dynamic ports but there is a race between getting them and using them
