### ISSUE TITLE
Failed: toomanyrequests docker pull rate limit

### ISSUE THREAD

**Issue by johanandren** [akka/akka-management#826]
https://travis-ci.com/github/akka/akka-management/jobs/460034786

I guess we just can't merge PRs too often ... :/ 

```
[error] toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
432[info] Removing intermediate image(s) (labeled "snp-multi-stage-id=570730e8-d22f-4829-8137-d7ccf792596b") 
433[info] Total reclaimed space: 0B
434[error] java.lang.RuntimeException: Nonzero exit value: 1
435[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:631)
436[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.$anonfun$projectSettings$49(DockerPlugin.scala:247)
437[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.$anonfun$projectSettings$49$adapted(DockerPlugin.scala:239)
```

**Comment by raboof** [comment]
again at https://travis-ci.com/github/akka/akka-management/jobs/461085166 ...

**Comment by seglo** [comment]
https://travis-ci.com/github/akka/akka-management/builds/212186459

**Comment by ignasi35** [comment]
again https://travis-ci.com/github/akka/akka-management/jobs/481860610#L829

**Comment by octonato** [comment]
again https://travis-ci.com/github/akka/akka-management/jobs/487035669#L695

we started to move some builds to GitHub actions because of this. Alpakka Kafka is done. JDBC plugin (done but release is broken, I'm still on it) and plan to move Akka Projections as soon as we have some bandwidth. 

Bottom line, any build that relies on docker should move. Anyway, I think this was already discussed, just reiterating.

**Comment by chbatey** [comment]
Happening a lot: https://travis-ci.com/github/akka/akka-management/builds/220937211

**Comment by octonato** [comment]
https://travis-ci.com/github/akka/akka-management/jobs/494006165#L517

**Comment by ignasi35** [comment]
Again https://travis-ci.com/github/akka/akka-management/jobs/497864770#L530

**Comment by ignasi35** [comment]
https://travis-ci.com/github/akka/akka-management/builds/223055982
