### ISSUE TITLE
Failed: Timed out removing lease 

### ISSUE THREAD

**Issue by octonato** [akka/akka-management#828]
https://travis-ci.com/github/akka/akka-management/jobs/466207654#L1153

```scala
- should be able to be created *** FAILED *** (1 second, 794 milliseconds)
[info]   The future returned an exception of type: akka.coordination.lease.LeaseTimeoutException, with message: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?. (KubernetesApiSpec.scala:86)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.coordination.lease.kubernetes.KubernetesApiSpec.$anonfun$new$2(KubernetesApiSpec.scala:86)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)

...

[info]   Cause: akka.coordination.lease.LeaseTimeoutException: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?
[info]   at akka.coordination.lease.kubernetes.internal.KubernetesApiImpl.$anonfun$makeRequest$2(KubernetesApiImpl.scala:251)
[info]   at akka.pattern.FutureTimeoutSupport.liftedTree1$1(FutureTimeoutSupport.scala:50)
[info]   at akka.pattern.FutureTimeoutSupport.$anonfun$after$1(FutureTimeoutSupport.scala:50)
[info]   at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:475)
[info]   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by ignasi35** [comment]
https://travis-ci.com/github/akka/akka-management/jobs/486154778#L5907

**Comment by octonato** [comment]
https://travis-ci.com/github/akka/akka-management/jobs/486904553#L3226
