### ISSUE TITLE
[Failed] ClusterHttpManagementRoutesSpec

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-management#848]
https://travis-ci.com/github/akka/akka-management/jobs/480307808#L4064

```
[info]   - when calling GET /cluster/domain-events *** FAILED *** (838 milliseconds)
[info]     A timeout occurred waiting for a future to complete. Waited 150 milliseconds. (ClusterHttpManagementRoutesSpec.scala:449)
[info]     org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
```

**Comment by patriknw** [comment]
150 millis looks like a small ScalaTest patience config.

@longshorej can you follow up here?

**Comment by longshorej** [comment]
Ah - I'll look into this, should have some time over the next week.

**Comment by ignasi35** [comment]
Again https://travis-ci.com/github/akka/akka-management/jobs/486017783#L6071

```
[info]   - when calling GET /cluster/domain-events *** FAILED *** (770 milliseconds)
[info]     A timeout occurred waiting for a future to complete. Waited 150 milliseconds. (ClusterHttpManagementRoutesSpec.scala:449)
[info]     org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[info]     at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[info]     at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]     at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]     at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]     at akka.cluster.http.management.scaladsl.ClusterHttpManagementRoutesSpec.$anonfun$new$34(ClusterHttpManagementRoutesSpec.scala:449)
[info]     at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]     at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
```
