### ISSUE TITLE
ClusterSingleton does not work with KubernetesLease

### ISSUE THREAD

**Issue by danischroeter** [akka/akka-management#852]
since ClusterSingletonManager uses his self.path in the lease name.

ClusterSingletonManager
```
  private val singletonLeaseName = s"${context.system.name}-singleton-${self.path}"

  override val log = Logging.withMarker(context.system, this)

  val lease: Option[Lease] = settings.leaseSettings.map(
    settings =>
      LeaseProvider(context.system)
        .getLease(singletonLeaseName, settings.leaseImplementation, cluster.selfAddress.hostPort))
```
I guess this should be `settings.singletonName`
I can create a pull request if my assumption is true...

```
akka.actor.InvalidActorNameException: Invalid actor path element [kubernetesLease5-im-singleton-akka://im/user/identityManager-singleton-im@10.52.105.235:9999], illegal character [/] at position: 35. Actor paths MUST: not start with `$`, include only ASCII letters and can only contain these special characters: -_.*$+:@&=,!~';.
	at akka.actor.ActorPath$.validatePathElement(ActorPath.scala:100)
	at akka.actor.ActorPath$.validatePathElement(ActorPath.scala:78)
	at akka.actor.dungeon.Children.checkName(Children.scala:250)
	at akka.actor.dungeon.Children.attachChild(Children.scala:52)
	at akka.actor.dungeon.Children.attachChild$(Children.scala:51)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:410)
	at akka.actor.ActorSystemImpl.systemActorOf(ActorSystem.scala:889)
	at akka.coordination.lease.kubernetes.KubernetesLease.<init>(KubernetesLease.scala:32)
	at akka.coordination.lease.kubernetes.KubernetesLease.<init>(KubernetesLease.scala:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:40)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:35)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$5(ReflectiveDynamicAccess.scala:48)
	at scala.util.Success.flatMap(Try.scala:258)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.coordination.lease.scaladsl.LeaseProvider.akka$coordination$lease$scaladsl$LeaseProvider$$loadLease(LeaseProvider.scala:102)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:69)
	at akka.coordination.lease.scaladsl.LeaseProvider$$anon$1.apply(LeaseProvider.scala:59)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at akka.coordination.lease.scaladsl.LeaseProvider.internalGetLease(LeaseProvider.scala:59)
	at akka.coordination.lease.scaladsl.LeaseProvider.getLease(LeaseProvider.scala:52)
	at akka.cluster.singleton.ClusterSingletonManager.$anonfun$lease$1(ClusterSingletonManager.scala:505)
	at scala.Option.map(Option.scala:242)
	at akka.cluster.singleton.ClusterSingletonManager.<init>(ClusterSingletonManager.scala:503)
	at akka.cluster.singleton.ClusterSingletonManager$.$anonfun$props$1(ClusterSingletonManager.scala:168)
	...
```

**Comment by johanandren** [comment]
(At least the stack trace is about `KubernetesLease` and not the `ClusterSingletonManager`)

**Comment by danischroeter** [comment]
@johanandren hmm why not replace 
private val singletonLeaseName = s"${context.system.name}-singleton-${self.path}"
with 
private val singletonLeaseName = s"${context.system.name}-singleton-${settings.singletonName}"

I guess if the actor name got sanitized the next thing would be kubernetes complaining about the name of the crdt :thinking:

**Comment by johanandren** [comment]
It would still fail here: https://github.com/akka/akka-management/blob/f16850b9caf3e556d23ef201bb8779e0135332d3/lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/KubernetesLease.scala#L30 (which is where the stacktrace you mention comes from)

**Comment by johanandren** [comment]
Regardless if that can be improved on the Akka side it is not safe to just use an arbitrary string provided from elsewhere as an actor name, so that's why I think fixing it here is more important/right. 

I agree though that using the singleton name over on the Akka side makes sense, but I may be missing out on something. Would it still fail with a fix here but current logic in Akka?

**Comment by danischroeter** [comment]
@johanandren Afaik then next thing is that the KubernetesLease tries to aquire the crdt which will fail because of kubernetes restrictions: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
That's why the lease name must be safe... 
`private val singletonLeaseName = s"${context.system.name}-singleton-${settings.singletonName}"`

But it will still be brittle since it imposes the rule that singleton names must be lowercase!
The best option would probably be to sanitize the lease name (toLower) or fail explicitly...

**Comment by johanandren** [comment]
Ah, I see, didn't think of that next step when I looked at this last week. I think we should anyway decouple the actor name and the lease name like this, that the requirements from k8 object names and Akka actor names align is a coincident.

Having the kubernetes lease "backend" sanitize the name so it works with k8 seems most convenient, but perhaps also a bit confusing/surprising so perhaps limiting accepted lease name, fail early and fix the singleton lease name makes more sense.

WDYT @chbatey ?

**Comment by chbatey** [comment]
There's also length. We have a utility (in a private project) that sanitizes names for k8s resources: https://github.com/lightbend/akka-platform-operator/blob/854610fdbfc111f903d4bd6d8716c6dc977f5fab/akka-operator/src/main/scala/akka/operator/common/Name.scala
