### ISSUE TITLE
Failed: ClusterBootstrapAutostartIntegrationSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#858]
Failing quite consistently in master, i'll look now

**Comment by ignasi35** [comment]
Hopefully fixed in #859

**Comment by octonato** [comment]
Failed again in:
https://travis-ci.com/github/akka/akka-management/jobs/486534725#L2253

This failure happened after #859 was merged.

```
[info] - should terminate a system when autostart fails *** FAILED *** (3 seconds, 69 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Waited 3 seconds. (ClusterBootstrapAutostartIntegrationSpec.scala:149)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at 
```

**Comment by octonato** [comment]
More timeouts
https://travis-ci.com/github/akka/akka-management/jobs/487022172#L5369

**Comment by octonato** [comment]
more of it
https://travis-ci.com/github/akka/akka-management/jobs/488215267#L2676-L2677
