### ISSUE TITLE
Unable to use akka-discovery-aws-api-async with multiple AWS SDK async http clients on the classpath

### ISSUE THREAD

**Issue by fgrutsch** [akka/akka-management#975]
### Versions used 

Akka version: transitive dependency of akka-management
Akka management version: 1.1.1

### Expected Behavior

I should be able to use `akka-discovery-aws-api-async` even if I have more than one AWS SDK async HTTP client implementation on the classpath.

### Actual Behavior

Right now I am unable to use `akka-discovery-aws-api-async` if I have more than one AWS SDK HTTP client implementation on the classpath, because the `EcsAsyncClient` doesn't explicitly define an httpClient and therefore does a lookup on the classpath (see description [here](https://github.com/matsluni/aws-spi-akka-http#usage)). 

In my production application, I came across that issue because I am also using [alpakka sqs](https://doc.akka.io/docs/alpakka/current/sqs.html), which transitively depends on https://github.com/matsluni/aws-spi-akka-http, therefore pulling in another AWS SDK async HTTP client.

My workaround right now is to use the sync `akka-discovery-aws-api` discovery method, as in my production app I only use AWS SDK async clients and therefore don't have any other AWS SDK sync HTTP clients on the classpath.

### Relevant logs

```
[ERROR] [12/02/2021 17:50:42.326] [ecsBootstrapDemoApp-akka.actor.internal-dispatcher-2] [akka://ecsBootstrapDemoApp/system/bootstrapCoordinator] Multiple HTTP implementations were found on the classpath. To avoid non-deterministic loading implementations, please explicitly provide an HTTP client via the client builders, set the software.amazon.awssdk.http.async.service.impl system property with the FQCN of the HTTP service to use as the default, or remove all but one HTTP implementation from the classpath
software.amazon.awssdk.core.exception.SdkClientException: Multiple HTTP implementations were found on the classpath. To avoid non-deterministic loading implementations, please explicitly provide an HTTP client via the client builders, set the software.amazon.awssdk.http.async.service.impl system property with the FQCN of the HTTP service to use as the default, or remove all but one HTTP implementation from the classpath
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
        at software.amazon.awssdk.core.internal.http.loader.ClasspathSdkHttpServiceProvider.loadService(ClasspathSdkHttpServiceProvider.java:62)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at software.amazon.awssdk.core.internal.http.loader.SdkHttpServiceProviderChain.loadService(SdkHttpServiceProviderChain.java:44)
        at software.amazon.awssdk.core.internal.http.loader.CachingSdkHttpServiceProvider.loadService(CachingSdkHttpServiceProvider.java:46)
        at software.amazon.awssdk.core.internal.http.loader.DefaultSdkAsyncHttpClientBuilder.buildWithDefaults(DefaultSdkAsyncHttpClientBuilder.java:41)
        at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveAsyncHttpClient$8(SdkDefaultClientBuilder.java:286)
        at java.base/java.util.Optional.orElseGet(Optional.java:369)
        at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveAsyncHttpClient(SdkDefaultClientBuilder.java:286)
        at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeAsyncConfiguration(SdkDefaultClientBuilder.java:237)
        at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:182)
        at software.amazon.awssdk.services.ecs.DefaultEcsAsyncClientBuilder.buildClient(DefaultEcsAsyncClientBuilder.java:28)
        at software.amazon.awssdk.services.ecs.DefaultEcsAsyncClientBuilder.buildClient(DefaultEcsAsyncClientBuilder.java:22)
        at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:130)
        at akka.discovery.awsapi.ecs.AsyncEcsServiceDiscovery.ecsClient$lzycompute(AsyncEcsServiceDiscovery.scala:51)
        at akka.discovery.awsapi.ecs.AsyncEcsServiceDiscovery.ecsClient(AsyncEcsServiceDiscovery.scala:44)
        at akka.discovery.awsapi.ecs.AsyncEcsServiceDiscovery.lookup(AsyncEcsServiceDiscovery.scala:62)
        at akka.management.cluster.bootstrap.internal.BootstrapCoordinator.akka$management$cluster$bootstrap$internal$BootstrapCoordinator$$discoverContactPoints(BootstrapCoordinator.scala:324)
        at akka.management.cluster.bootstrap.internal.BootstrapCoordinator$$anonfun$receive$1.applyOrElse(BootstrapCoordinator.scala:205)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.management.cluster.bootstrap.internal.BootstrapCoordinator.akka$actor$Timers$$super$aroundReceive(BootstrapCoordinator.scala:132)
        at akka.actor.Timers.aroundReceive(Timers.scala:56)
        at akka.actor.Timers.aroundReceive$(Timers.scala:41)
        at akka.management.cluster.bootstrap.internal.BootstrapCoordinator.aroundReceive(BootstrapCoordinator.scala:132)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Reproducible Test Case

See [this linked branch](https://github.com/fgrutsch/akka-management/commit/966c68d6ebebbfebf894617215240226efd4aaef) with a demo test case and also the comment for the fix. 

`sbt integration-test-aws-api-ecs/run` will produce the error log above.

Would speak anything against explicitly specifying an httpClient? I wouldn't say so, because it doesn't change/break the existing usage/API. If it's fine I can open a PR with a proper fix the next days.

**Comment by johanandren** [comment]
Sounds like being able to explicitly specify is good, as long as it's backwards compatible. Please go ahead and PR.

**Comment by johanandren** [comment]
Looks like we forgot to close this when #986 was merged.
